### ISSUE TITLE
Reason of Invalidation

### ISSUE THREAD

**Issue by SSgumS** [VahidN/DNTCaptcha.Core#50]
Hi,

It would be great if the default validator service could return the reason of invalidation.
I want to have a different error message when cookie is not valid. For example telling user that your login form has been expired.
Based on current validator service I don't have any ways to do this except writing my own validator service.
I think it's really essential for a validator service to return the reason if a captcha entry is not valid.

Thanks in advance

**Comment by VahidN** [comment]
You can see the reason with `_logger.LogDebug` [here](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/Providers/DNTCaptchaValidatorService.cs). Why? Because showing too much info to the user/a possible attacker is not good for the security. They should know only their input is wrong and they should try again. detail error messages are good for debugging a web site for attackers.

**Comment by SSgumS** [comment]
I see.
Thank you
